### ISSUE TITLE
"Maximum Stock Quantity" which should show on the home page graph does not display

### ISSUE THREAD

**Issue by LakshmiCHAI** [chailmis/chailmis-android#135]
Severity: Medium

**Comment by reneeorser** [comment]
Depending on 127. should be fixed with 127.

**Comment by chai-lmis** [comment]
Maximum stock still does not display on the bar chart on the home page

**Comment by chai-lmis** [comment]
Max stock level on the home page bar chart is at the same level for all commodities (thought max stock from the bin cards are different)

**Comment by jobasiimwe** [comment]
Some times, the stock on hand of one commodity is so high that the scale of the graph is skewed...the max and min on all bars and soh on the remaining 4 bars seems to be exacitly the same because 290,270,300 and 295 will appear to be the same if they are plotted on a graph with a value like 5000. 
If you reduce the quantity of the skewed value to close to the rest, the max min and stock on hand will appear different.

**Comment by chai-lmis** [comment]
ok, if that is the case, then when we have "real" data calculating correctly we should not have this problem

**Comment by chai-lmis** [comment]
will it be possible to include values for the minimum orders displayed in the bar

**Comment by jobasiimwe** [comment]
Hello Egwuma, Did you mean Minimum orders or Minimum Stock?

**Comment by chai-lmis** [comment]
i meant minimum orders as that indicator is more important for early alert warning for stock out

**Comment by jobasiimwe** [comment]
By "minimum orders" the client actually meant Minimum Stock Level, (formally called Minimum Threshold). This value should be showing on the graph bars always.

**Comment by cvaldez519** [comment]
TESTED. Both max and min levels are appearing on the graph.

**Comment by chai-lmis** [comment]
The max and min levels do not appear on the graph anymore, tested this using  the updated APK from the F-Droid

**Comment by chai-lmis** [comment]
the problem has been identified from the server end, the scripts to populate these figures had not been run
